[package]
name = "oxybox"
version.workspace = true
edition = "2024"
description = "Rust bindings/API for Box2D."
license = "MIT"
repository = "https://github.com/imlazyeye/oxybox"
readme = "../README.md"

[dependencies]
glam.workspace = true

sys = { package = "oxybox-sys", version = "0.2.0", path = "../oxybox-sys" }
thiserror = "2.0.20"
